# Generated by Django 4.2.10 on 2025-08-25 12:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('long_url', models.TextField()),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Treatment name', max_length=255)),
                ('category', models.CharField(help_text='Treatment category', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Creation timestamp', null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Last update timestamp', null=True)),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'db_table': 'treatments',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('history', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session_data',
                'indexes': [models.Index(fields=['application_id'], name='session_dat_applica_9f6cda_idx'), models.Index(fields=['session_id'], name='session_dat_session_30f6e4_idx')],
            },
        ),
    ]
