# Generated by Django 4.2.20 on 2025-05-12 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('history', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session_data',
                'indexes': [models.Index(fields=['application_id'], name='session_dat_applica_9f6cda_idx'), models.Index(fields=['session_id'], name='session_dat_session_30f6e4_idx'), models.Index(fields=['user_id'], name='session_dat_user_id_b40a22_idx')],
            },
        ),
    ]
