# Generated by Django 4.2.10 on 2025-05-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondata',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
