# Generated by Django 4.2.10 on 2025-05-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpapp', '0002_alter_sessiondata_user_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sessiondata',
            name='session_dat_user_id_b40a22_idx',
        ),
        migrations.RemoveField(
            model_name='sessiondata',
            name='user_id',
        ),
    ]
