# Generated by Django 4.2.10 on 2025-06-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpapp', '0003_remove_sessiondata_session_dat_user_id_b40a22_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
