# Generated by Django 4.2.10 on 2025-07-30 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpapp', '0006_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Creation timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Last update timestamp', null=True),
        ),
    ]
